// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmyuh0ySQyCA3M430IUQxLip8RkZt7Rqc',
    appId: '1:350684520144:web:42412044ccc9a2a4ff48d5',
    messagingSenderId: '350684520144',
    projectId: 'myapp-8cd3f',
    authDomain: 'myapp-8cd3f.firebaseapp.com',
    databaseURL: 'https://myapp-8cd3f-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-8cd3f.firebasestorage.app',
    measurementId: 'G-W0GSP9P6K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYHdPYsQdiju4MYzb4GuDN6yydNC1mBNs',
    appId: '1:350684520144:android:642e68d5bf508ec5ff48d5',
    messagingSenderId: '350684520144',
    projectId: 'myapp-8cd3f',
    databaseURL: 'https://myapp-8cd3f-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-8cd3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bEevY9ihSAsWMfN0S1-N8_qKbn1y4dU',
    appId: '1:350684520144:ios:a6ceffbbe36d377aff48d5',
    messagingSenderId: '350684520144',
    projectId: 'myapp-8cd3f',
    databaseURL: 'https://myapp-8cd3f-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-8cd3f.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );
}
